#!/bin/bash

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🚀 DEPLOYING SUBSCRIPTION FIX"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

echo "✅ WHAT'S FIXED:"
echo "  1. Subscriptions created immediately on payment verify"
echo "  2. Frontend reloads subscription data automatically"
echo "  3. Dashboard navigation works correctly"
echo "  4. Active subscription displays in dashboard"
echo ""

cd supabase

echo "📤 Deploying Edge Function with --no-verify-jwt..."
supabase functions deploy payments-simple --no-verify-jwt

if [ $? -eq 0 ]; then
    echo ""
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo "✅ DEPLOYMENT SUCCESSFUL!"
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo ""
    echo "📋 Next steps:"
    echo ""
    echo "1. Start dev server:"
    echo "   cd .."
    echo "   npm run dev"
    echo ""
    echo "2. Test payment flow:"
    echo "   - Open http://localhost:5173 (Incognito)"
    echo "   - Login"
    echo "   - Settings → Subscription → Subscribe"
    echo "   - Complete payment"
    echo "   - ✅ Subscription created immediately"
    echo "   - ✅ Dashboard navigation works"
    echo "   - ✅ Active badge shows"
    echo ""
    echo "3. Watch logs in separate terminal:"
    echo "   cd supabase"
    echo "   supabase functions logs payments-simple --follow"
    echo ""
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo "🎉 ALL ISSUES FIXED! TEST NOW!"
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
else
    echo ""
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo "❌ DEPLOYMENT FAILED"
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo ""
    echo "Common issues:"
    echo ""
    echo "1. Secrets not set:"
    echo "   supabase secrets set SERVICE_ROLE_KEY=YOUR_KEY"
    echo "   supabase secrets set PAYSTACK_SECRET_KEY=YOUR_KEY"
    echo "   supabase secrets set FRONTEND_URL=http://localhost:5173"
    echo ""
    echo "2. Not logged in to Supabase:"
    echo "   supabase login"
    echo ""
    echo "3. Not linked to project:"
    echo "   supabase link --project-ref pkzpifdocmmzowvjopup"
    echo ""
fi

cd ..
